// const selectorsMap = {
//     'secondIcon': '//div[@data-autoid="sliderWithIcons:icon2"]',
//     'acceptCookiesButton': '//button[@id="onetrust-accept-btn-handler"]',
//     'statement1Text': '//div[@id="TextStatement-1"]',
//     'saveSpaceTechButton': '//button[@aria-label="Safe Space Technology"]',
//     'acclaimedLifeSaverButton': '//button[@aria-label="Our most acclaimed lifesaver"]',
//     'dataBasedSearchButton': '//button[@aria-label="Data-based research"]',
//     'sliderHeadlineText1': '(//h3[contains(text(), "Safe Space Technology")])[2]',
//     'sliderHeadlineText2': '(//h3[contains(text(), "Our most acclaimed lifesaver")])[2]',
//     'sliderHeadlineText3': '(//h3[contains(text(), "Data-based research")])[2]',
//     'safetySliderLeftCarousel': '(//button[@aria-label="Previous slide"])[1]',
//     'safetySliderRightCarousel': '(//button[@aria-label="Next slide"])[1]',
//     'productListSliderLeftCarousel': '(//button[@aria-label="Previous slide"])[2]',
//     'productListSliderRightCarousel': '(//button[@aria-label="Next slide"])[2]',
//     'productsList': '//div[@role="list"]/div[@data-autoid="springCarouselPane:carouselItem"]//h3',
//     'productCodesLists': '(//div[@role="list"]/div[@data-autoid="springCarouselPane:carouselItem"]//h3)/span[1]',
//     'productNamesLists': '(//div[@role="list"]/div[@data-autoid="springCarouselPane:carouselItem"]//h3)/span[2]',
//     'productListHeaderText': '//h2[text()= "All recharge models"]',    
// };
// export default selectorsMap;